import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<nav
					style={{
						textAlign: "center",
						padding: "10px",
						borderBottom: "1px solid #ccc",
					}}
				>
					<Link href="/">Home</Link> |<Link href="/dashboard">Dashboard</Link> |
					<Link href="/about">About</Link> |
					<Link href="/contacts">Contacts</Link>
				</nav>
				<main>{children}</main>
			</body>
		</html>
	);
}
